// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO users (
    email, username, password_hash, display_name
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, email, username, password_hash, display_name, created_at, updated_at
`

type CreateAuthorParams struct {
	Email        string
	Username     string
	PasswordHash string
	DisplayName  sql.NullString
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createAuthor,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
