// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    user_id, title, url, description
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, title, url, description, created_at, updated_at
`

type CreateVideoParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Title       string    `json:"title"`
	Url         string    `json:"url"`
	Description string    `json:"description"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.UserID,
		arg.Title,
		arg.Url,
		arg.Description,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
